/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.conversorGUI;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.util.concurrent.TimeUnit;
import javax.swing.UIManager;

/**
 *
 * @author diego
 */
public class DivisasMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public DivisasMenu() {
//        FlatDarkLaf.setup();
//        setVisible(true);
//        UIManager.put( "Button.arc", 20 );
        initComponents();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        titleDiv = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        currencyLbl = new javax.swing.JLabel();
        currencyField = new javax.swing.JTextField();
        changeBtn = new javax.swing.JButton();
        currencyTo = new javax.swing.JComboBox<>();
        currencyFrom = new javax.swing.JComboBox<>();
        convertirBtn = new javax.swing.JButton();
        resultadoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(650, 750));

        background.setBackground(new java.awt.Color(221, 230, 237));
        background.setPreferredSize(new java.awt.Dimension(650, 750));
        background.setRequestFocusEnabled(false);

        titleBar.setBackground(new java.awt.Color(39, 55, 77));
        titleBar.setPreferredSize(new java.awt.Dimension(550, 80));

        titleDiv.setBackground(new java.awt.Color(255, 255, 255));
        titleDiv.setFont(new java.awt.Font("Inconsolata", 0, 24)); // NOI18N
        titleDiv.setForeground(new java.awt.Color(221, 230, 237));
        titleDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyLogo.png"))); // NOI18N
        titleDiv.setText("Conversor de Divisas");
        titleDiv.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        regresarBtn.setBackground(new java.awt.Color(39, 55, 77));
        regresarBtn.setFont(new java.awt.Font("Inconsolata", 1, 14)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(221, 230, 237));
        regresarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow1.png"))); // NOI18N
        regresarBtn.setBorderPainted(false);
        regresarBtn.setFocusable(false);
        regresarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regresarBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(regresarBtn)
                .addGap(76, 76, 76)
                .addComponent(titleDiv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        currencyLbl.setFont(new java.awt.Font("Inconsolata", 0, 16)); // NOI18N
        currencyLbl.setForeground(new java.awt.Color(39, 55, 77));
        currencyLbl.setText("Monto a convertir:");

        currencyField.setBackground(new java.awt.Color(221, 230, 237));
        currencyField.setFont(new java.awt.Font("Inconsolata", 0, 26)); // NOI18N
        currencyField.setForeground(new java.awt.Color(39, 55, 77));
        currencyField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(39, 55, 77))
        );
        currencyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyFieldActionPerformed(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(221, 230, 237));
        changeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/changeIcon.png"))); // NOI18N
        changeBtn.setBorderPainted(false);

        currencyTo.setBackground(new java.awt.Color(39, 55, 77));
        currencyTo.setFont(new java.awt.Font("Inconsolata", 0, 18)); // NOI18N
        currencyTo.setForeground(new java.awt.Color(221, 230, 237));
        currencyTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currencyTo.setFocusable(false);
        currencyTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyToActionPerformed(evt);
            }
        });

        currencyFrom.setBackground(new java.awt.Color(39, 55, 77));
        currencyFrom.setFont(new java.awt.Font("Inconsolata", 0, 18)); // NOI18N
        currencyFrom.setForeground(new java.awt.Color(221, 230, 237));
        currencyFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currencyFrom.setFocusable(false);
        currencyFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyFromActionPerformed(evt);
            }
        });

        convertirBtn.setBackground(new java.awt.Color(39, 55, 77));
        convertirBtn.setFont(new java.awt.Font("Inconsolata", 0, 18)); // NOI18N
        convertirBtn.setForeground(new java.awt.Color(221, 230, 237));
        convertirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowback1.png"))); // NOI18N
        convertirBtn.setText("Convertir");
        convertirBtn.setBorderPainted(false);
        convertirBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        resultadoLbl.setFont(new java.awt.Font("Inconsolata", 0, 20)); // NOI18N
        resultadoLbl.setForeground(new java.awt.Color(39, 55, 77));
        resultadoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoLbl.setText("Ingrese un monto a convertir");
        resultadoLbl.setToolTipText("");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currencyLbl)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(currencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(currencyTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currencyFrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convertirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultadoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(currencyLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currencyField))
                .addGap(80, 80, 80)
                .addComponent(currencyFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(currencyTo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(convertirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(resultadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void currencyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyFieldActionPerformed

    private void currencyToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyToActionPerformed

    private void currencyFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyFromActionPerformed
                                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDarkLaf.setup();
        UIManager.put( "Button.arc", 20 );
        UIManager.put("Component.arc", 20);
        UIManager.put("Component.disabledBorderColor", true);
        UIManager.put("ComboBox.buttonArrowColor", new Color(0xDDE6ED));
        UIManager.put("Component.arrowType", "triangle" );
        UIManager.put("ComboBox.buttonBackground", new Color(0x27374D));
        UIManager.put("ComboBox.popupBackground", new Color(0x27374D));
        UIManager.put("ComboBox.selectionForeground", new Color(0xDDE6ED));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DivisasMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton changeBtn;
    private javax.swing.JButton convertirBtn;
    private javax.swing.JTextField currencyField;
    private javax.swing.JComboBox<String> currencyFrom;
    private javax.swing.JLabel currencyLbl;
    private javax.swing.JComboBox<String> currencyTo;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JLabel resultadoLbl;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titleDiv;
    // End of variables declaration//GEN-END:variables
}
