/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.conversorGUI;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author diego
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        FlatDarkLaf.setup();
        UIManager.put( "Button.arc", 20 );
        setVisible(true);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        divisasBtn = new javax.swing.JButton();
        tempBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(logo);
        setResizable(false);
        setSize(new java.awt.Dimension(650, 750));

        background.setBackground(new java.awt.Color(221, 230, 237));
        background.setPreferredSize(new java.awt.Dimension(650, 750));
        background.setRequestFocusEnabled(false);

        titleBar.setBackground(new java.awt.Color(39, 55, 77));
        titleBar.setPreferredSize(new java.awt.Dimension(550, 80));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Inconsolata", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(221, 230, 237));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoAlura.png"))); // NOI18N
        title.setText("Conversor Alura - ONE");

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(14, 14, 14))
        );

        divisasBtn.setBackground(new java.awt.Color(39, 55, 77));
        divisasBtn.setFont(new java.awt.Font("Inconsolata", 0, 20)); // NOI18N
        divisasBtn.setForeground(new java.awt.Color(221, 230, 237));
        divisasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money.png"))); // NOI18N
        divisasBtn.setText("Divisas");
        divisasBtn.setBorderPainted(false);
        divisasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        divisasBtn.setFocusable(false);
        divisasBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        divisasBtn.setIconTextGap(2);
        divisasBtn.setPreferredSize(new java.awt.Dimension(180, 80));
        divisasBtn.setVerifyInputWhenFocusTarget(false);
        divisasBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        divisasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisasBtnActionPerformed(evt);
            }
        });

        tempBtn.setBackground(new java.awt.Color(39, 55, 77));
        tempBtn.setFont(new java.awt.Font("Inconsolata", 0, 20)); // NOI18N
        tempBtn.setForeground(new java.awt.Color(221, 230, 237));
        tempBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/temperature.png"))); // NOI18N
        tempBtn.setText("Temperatura");
        tempBtn.setBorderPainted(false);
        tempBtn.setFocusable(false);
        tempBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tempBtn.setIconTextGap(2);
        tempBtn.setPreferredSize(new java.awt.Dimension(180, 80));
        tempBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tempBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tempBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(divisasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(tempBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 292, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tempBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempBtnActionPerformed
        if(evt.getSource() == tempBtn) {
            this.dispose();
            TemperaturaMenu tempMenu = new TemperaturaMenu();
        }
    }//GEN-LAST:event_tempBtnActionPerformed

    private void divisasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisasBtnActionPerformed
        if(evt.getSource() == divisasBtn) {
            this.dispose();
            DivisasMenu divisasMenu = new DivisasMenu();
        }
    }//GEN-LAST:event_divisasBtnActionPerformed
                                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDarkLaf.setup();
        UIManager.put( "Button.arc", 20 );

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    private ImageIcon icono = new ImageIcon(getClass().getResource("/logoAlura.png"));
    private final Image logo = icono.getImage();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton divisasBtn;
    private javax.swing.JButton tempBtn;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
