/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.conversorGUI;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author diego
 */
public class TemperaturaMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public TemperaturaMenu() {
        FlatDarkLaf.setup();
        UIManager.put( "Button.arc", 20 );
        UIManager.put("Component.arc", 20);
        UIManager.put("Component.disabledBorderColor", true);
        UIManager.put("ComboBox.buttonArrowColor", new Color(0xDDE6ED));
        UIManager.put("Component.arrowType", "triangle" );
        UIManager.put("ComboBox.buttonBackground", new Color(0x27374D));
        UIManager.put("ComboBox.popupBackground", new Color(0x27374D));
        UIManager.put("ComboBox.selectionForeground", new Color(0xDDE6ED));
//        FlatDarkLaf.setup();
        setVisible(true);
//        UIManager.put( "Button.arc", 20 );
        initComponents();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        titleTemp = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        degreesLbl = new javax.swing.JLabel();
        degreeField = new javax.swing.JTextField();
        changeBtn = new javax.swing.JButton();
        degreeTo = new javax.swing.JComboBox<>();
        degreeFrom = new javax.swing.JComboBox<>();
        convertirBtn = new javax.swing.JButton();
        resultadoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(650, 750));

        background.setBackground(new java.awt.Color(221, 230, 237));
        background.setPreferredSize(new java.awt.Dimension(650, 750));
        background.setRequestFocusEnabled(false);

        titleBar.setBackground(new java.awt.Color(39, 55, 77));
        titleBar.setPreferredSize(new java.awt.Dimension(550, 80));

        titleTemp.setBackground(new java.awt.Color(255, 255, 255));
        titleTemp.setFont(new java.awt.Font("Inconsolata", 0, 24)); // NOI18N
        titleTemp.setForeground(new java.awt.Color(221, 230, 237));
        titleTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/temperatureLogo.png"))); // NOI18N
        titleTemp.setText("Conversor de Temperatura");
        titleTemp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        regresarBtn.setBackground(new java.awt.Color(39, 55, 77));
        regresarBtn.setFont(new java.awt.Font("Inconsolata", 1, 14)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(221, 230, 237));
        regresarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow1.png"))); // NOI18N
        regresarBtn.setBorderPainted(false);
        regresarBtn.setFocusable(false);
        regresarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regresarBtn.setLabel("");
        regresarBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(regresarBtn)
                .addGap(53, 53, 53)
                .addComponent(titleTemp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        degreesLbl.setFont(new java.awt.Font("Inconsolata", 0, 16)); // NOI18N
        degreesLbl.setForeground(new java.awt.Color(39, 55, 77));
        degreesLbl.setText("Grados a convertir:");

        degreeField.setBackground(new java.awt.Color(221, 230, 237));
        degreeField.setFont(new java.awt.Font("Inconsolata", 0, 26)); // NOI18N
        degreeField.setForeground(new java.awt.Color(39, 55, 77));
        degreeField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(39, 55, 77))
        );
        degreeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeFieldActionPerformed(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(221, 230, 237));
        changeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/changeIcon.png"))); // NOI18N
        changeBtn.setBorderPainted(false);

        degreeTo.setBackground(new java.awt.Color(39, 55, 77));
        degreeTo.setFont(new java.awt.Font("Inconsolata", 0, 18)); // NOI18N
        degreeTo.setForeground(new java.awt.Color(221, 230, 237));
        degreeTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        degreeTo.setFocusable(false);
        degreeTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeToActionPerformed(evt);
            }
        });

        degreeFrom.setBackground(new java.awt.Color(39, 55, 77));
        degreeFrom.setFont(new java.awt.Font("Inconsolata", 0, 18)); // NOI18N
        degreeFrom.setForeground(new java.awt.Color(221, 230, 237));
        degreeFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        degreeFrom.setFocusable(false);

        convertirBtn.setBackground(new java.awt.Color(39, 55, 77));
        convertirBtn.setFont(new java.awt.Font("Inconsolata", 0, 18)); // NOI18N
        convertirBtn.setForeground(new java.awt.Color(221, 230, 237));
        convertirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowback1.png"))); // NOI18N
        convertirBtn.setText("Convertir");
        convertirBtn.setBorderPainted(false);
        convertirBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        resultadoLbl.setFont(new java.awt.Font("Inconsolata", 0, 20)); // NOI18N
        resultadoLbl.setForeground(new java.awt.Color(39, 55, 77));
        resultadoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoLbl.setText("Ingrese una cantidad a convertir");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(degreesLbl)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(degreeField, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(degreeTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(degreeFrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convertirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultadoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(degreesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(degreeField))
                .addGap(80, 80, 80)
                .addComponent(degreeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(degreeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(convertirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(resultadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        if (evt.getSource() == regresarBtn){
            this.dispose();
            MainMenu menuPrincipal = new MainMenu();
        }
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void degreeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeFieldActionPerformed

    private void degreeToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeToActionPerformed
                                 
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        TemperaturaMenu menu = new TemperaturaMenu();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton changeBtn;
    private javax.swing.JButton convertirBtn;
    private javax.swing.JTextField degreeField;
    private javax.swing.JComboBox<String> degreeFrom;
    private javax.swing.JComboBox<String> degreeTo;
    private javax.swing.JLabel degreesLbl;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JLabel resultadoLbl;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titleTemp;
    // End of variables declaration//GEN-END:variables
}
